import type { Metadata } from "next";
import { Poppins, Sacramento } from "next/font/google";
import "./globals.css";

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Footer from "@/ui/footer";
config.autoAddCss = false;

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: '--font-poppins',
});

const sacramento = Sacramento({
  subsets: ["latin"],
  weight: ["400"],
  variable: '--font-sacramento',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sacramento.variable} ${poppins.variable} flex min-h-screen w-screen flex-col items-center bg-slate-700 justify-center`}>
        {children}
        <Footer / >
      </body>
    </html>
  );
}
